//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spring2015
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class BKLevel1
    {
        public BKLevel1()
        {
            this.BKLevel2 = new HashSet<BKLevel2>();
        }
    
        public int BKLevel1ID { get; set; }
        public int CurriculumID { get; set; }
        [Display(Name = "BkLevel1Number")]
        public int NumberLevel1 { get; set; }
        [Required(ErrorMessage = "**Please Provide Name", AllowEmptyStrings = false)]
        public string Name { get; set; }
        [Required(ErrorMessage = "**Please Provide ShortName", AllowEmptyStrings = false)]
        public string ShortName { get; set; }
        public virtual ICollection<BKLevel2> BKLevel2 { get; set; }
        public virtual Curriculum Curriculum { get; set; }
    }
}
