//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spring2015
{
    using System;
    using System.Collections.Generic;
    
    public partial class BKLevel1
    {
        public BKLevel1()
        {
            this.BKLevel2 = new HashSet<BKLevel2>();
            this.BKLevel21 = new HashSet<BKLevel2>();
        }
    
        public int BKLevel1ID { get; set; }
        public Nullable<int> CurriculumID { get; set; }
        public Nullable<int> NumberLevel { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string Purpose { get; set; }
    
        public virtual ICollection<BKLevel2> BKLevel2 { get; set; }
        public virtual ICollection<BKLevel2> BKLevel21 { get; set; }
        public virtual Curriculum Curriculum { get; set; }
    }
}
