//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spring2015
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.Outcomes = new HashSet<Outcome>();
        }
    
        public int CourseID { get; set; }
        public Nullable<int> SectionID { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string CatalogCopy { get; set; }
        public string Prerequisites { get; set; }
        public string YearInCurriculum { get; set; }
        public string Scope { get; set; }
        public string Topics { get; set; }
        public string Discussion { get; set; }
    
        public virtual ICollection<Outcome> Outcomes { get; set; }
        public virtual Section Section { get; set; }
    }
}
