//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spring2015
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Login
    {
        public int UserID { get; set; }
        [Required(ErrorMessage = "**Please Provide your Username", AllowEmptyStrings = false)]
        public string Username { get; set; }
        [Required(ErrorMessage = "**Please Provide your Password", AllowEmptyStrings = false)]
        public string Password { get; set; }
        public string PasswordSalt { get; set; }
    }
}
