//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spring2015
{
    using System;
    using System.Collections.Generic;
    
    public partial class Outcome
    {
        public Outcome()
        {
            this.OutcomeinBK2 = new HashSet<OutcomeinBK2>();
            this.SubskillsinOutcomes = new HashSet<SubskillsinOutcome>();
        }
    
        public int OutcomeID { get; set; }
        public int CourseID { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public Nullable<int> DepthOfKnowledge { get; set; }
        public int OutcomeNumber { get; set; }
        public int SectionNumber { get; set; }
        public int CourseNumber { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual ICollection<OutcomeinBK2> OutcomeinBK2 { get; set; }
        public virtual ICollection<SubskillsinOutcome> SubskillsinOutcomes { get; set; }
    }
}
