//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spring2015
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubskillsinOutcome
    {
        public int SubskillsinoutcomeID { get; set; }
        public Nullable<int> OutcomeID { get; set; }
        public Nullable<int> SubskillsID { get; set; }
    
        public virtual Outcome Outcome { get; set; }
        public virtual SubSkill SubSkill { get; set; }
    }
}
