//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spring2015.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BKLevel2
    {
        public BKLevel2()
        {
            this.tblSubskillsinBk2 = new HashSet<SubskillsinBk2>();
            this.tblOutcomeinBK2 = new HashSet<OutcomeinBK2>();
        }
    
        public int BKLevel2ID { get; set; }
        public Nullable<int> BKLevel1ID { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public Nullable<int> InitialDate { get; set; }
        public Nullable<int> ReleaseDate { get; set; }
        public Nullable<int> CloseDate { get; set; }
        public string Purpose { get; set; }
    
        public virtual BKLevel1 tblBKLevel1 { get; set; }
        public virtual ICollection<SubskillsinBk2> tblSubskillsinBk2 { get; set; }
        public virtual ICollection<OutcomeinBK2> tblOutcomeinBK2 { get; set; }
    }
}
