//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spring2015.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BKLevel1
    {
        public BKLevel1()
        {
            this.tblBKLevel2 = new HashSet<BKLevel2>();
        }
    
        public int BKLevel1ID { get; set; }
        public Nullable<int> CurriculumID { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public Nullable<int> InitialDate { get; set; }
        public Nullable<int> ReleaseDate { get; set; }
        public Nullable<int> CloseDate { get; set; }
        public string Purpose { get; set; }
    
        public virtual Curriculum tblCurriculum { get; set; }
        public virtual ICollection<BKLevel2> tblBKLevel2 { get; set; }
    }
}
