//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spring2015.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkillSet
    {
        public SkillSet()
        {
            this.Skills = new HashSet<Skill>();
        }
    
        public int SkillsetID { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public Nullable<int> CurriculumID { get; set; }
    
        public virtual Curriculum Curriculum { get; set; }
        public virtual ICollection<Skill> Skills { get; set; }
    }
}
